export const en = {
  nav: {
    home: "Home",
    explore: "Explore",
    profile: "Profile",
    admin: "Admin",
    newPost: "New Post",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Messages",
      social: "Social Network",
    },
    window: {
      minimize: "Minimize",
      close: "Close",
    },
    taskbar: {
      start: "Start",
    },
  },
  messagesApp: {
    title: "Messages",
    inbox: "Inbox",
    selectMessage: "Select a message to read",
    fromLabel: "From",
    time: {
      minutesAgo: "{{count}} min ago",
      hoursAgo: "{{count}} h ago",
    },
    messages: {
      welcome: {
        from: "The Boss",
        subject: "Welcome to the team",
        content:
          "Welcome to our investigation team! Your first mission is to get familiar with the corporate social network. Explore profiles and look for clues.",
      },
      hint1: {
        from: "The Boss",
        subject: "First hint",
        content:
          "I've noticed suspicious activity in some profiles. Check recent posts and look for unusual patterns. The user @admin may have relevant information.",
      },
      hint2: {
        from: "The Boss",
        subject: "Additional clue",
        content:
          "Comments on the most popular posts may contain hidden codes. Pay attention to ALL CAPS words and repeated emojis.",
      },
    },
  },
  createPost: {
    placeholder: "What is happening?!",
    fileTooBig: "file must be less than 20mb",
    invalidFileType: "file must be a Video (MP4/MOV) or an Image (JPEG/PNG)",
    publish: "Post",
  },
  post: {
    editPost: "Edit Post",
    deletePost: "Delete Post",
    verifiedAccount: "Verified account",
    linkCopied: "Link successfully copied",
  },
  home: {
    sortBy: {
      trending: "Trending",
      oldest: "Oldest",
      latest: "Latest",
      posts: "Posts",
    },
    noPosts: "Sorry, there no posts to show! Follow people to see their posts.",
  },
  profile: {
    noPosts: "You have not added any posts!",
    editProfile: "Edit Profile",
    following: "Following",
    followers: "Followers",
    posts: "Posts",
    joined: "Joined",
    follow: "Follow",
    verifiedAccount: "Verified account",    backToGame: "Back to Game",  },
  explore: {
    caughtUp: "You are all caught up!",
  },
  admin: {
    title: "Admin Panel",
    users: "Users",
    posts: "Posts",
    suspectUsers: "Suspect Users",
    hint: "Hint",
    bot: "Bot",
    human: "Human",
    noSuspects: "No suspect users at this time",
    userBlocked: "User blocked as AI",
    userClassified: "User classified as Human",
    classified: "Classified",
    submit: "Submit Classification",
    resultTitle: "Your Classification Result",
    perfectScore: "Perfect Score!",
    score: "Score",
    allCorrect: "Excellent! You've correctly identified all users.",
    tryAgain: "Some classifications are incorrect. Try again!",
    playAgain: "Play Again",
    hintTitle: "Bot Account Indicators",
    hintContent: {
      temporalActivity: "Suspicious temporal activity: Posts at very regular intervals or unusual times",
      repetitiveContent: "Repetitive content: Very similar or identical messages between posts",
      excessLinks: "Excess links: Many posts with external links",
      noInteraction: "No interaction: Doesn't respond to comments or mentions",
      abnormalRatio: "Abnormal ratio: Many followers but little real interaction",
      singleTopic: "Single topic: Only posts about a very specific topic",
      recentAccount: "Recent account: New account with immediate high activity",
    },
  },
  editPost: {
    title: "Edit Post",
    save: "Save",
    cancel: "Cancel",
  },
  comments: {
    placeholder: "Write a comment...",
    post: "Post",
    noComments: "No comments yet",
    reply: "Reply",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
  },
  time: {
    justNow: "just now",
    minuteAgo: "minute ago",
    minutesAgo: "minutes ago",
    hourAgo: "hour ago",
    hoursAgo: "hours ago",
    dayAgo: "day ago",
    daysAgo: "days ago",
    weekAgo: "week ago",
    weeksAgo: "weeks ago",
    monthAgo: "month ago",
    monthsAgo: "months ago",
    yearAgo: "year ago",
    yearsAgo: "years ago",
  },
  statsPanel: {
    title: "System Status",
    misinformationLevel: "Misinformation Level",
    suspiciousActivityDetected: "⚠️ Suspicious activity detected on the network",
    detailedAnalysis: "Detailed Analysis",
    postsLastHour: "Posts (recent days)",
    percentageAboveNormal: "{{percentage}}% above normal",
    newUsersLastHour: "New users (recent days)",
    massAccountCreation: "⚠️ Massive account creation detected",
    viralHashtags: "Viral Hashtags",
    botActivity: "Bot Activity",
    detected: "detected",
    suspiciousInteractions: "{{percentage}}% of suspicious interactions",
    averageEngagement: "Average Engagement",
    likes: "Likes",
    comments: "Comments",
    shares: "Shares",
    recentAccounts: "Recent Accounts (recent days)",
    abnormalProportionNewAccounts: "⚠️ Abnormal proportion of new accounts",
    tip: "💡 Tip: Investigate profiles with suspicious patterns",
    statusHigh: "HIGH",
    statusMedium: "MEDIUM",
    statusLow: "LOW",
    systemSecure: "System Status: All Clear!",
  },
  errors: {
    pageNotFound: "Page not found",
    goHome: "Go to Home",
  },
};
