export const en = {
  "langKey": "en",
  "nav": {
    "home": "Home",
    "explore": "Explore",
    "profile": "Profile",
    "admin": "Suspicious Accounts",
    "aiContent": "AI Generated Content",
    "aiIncorrectUses": "AI Incorrect Uses",
    "newPost": "New Post"
  },
  "header": {
    "appName": "ECHO"
  },
  "desktop": {
    "apps": {
      "messages": "Messages",
      "social": "Social Network",
      "files": "Files"
    },
    "window": {
      "minimize": "Minimize",
      "close": "Close"
    },
    "taskbar": {
      "start": "Start"
    },
    "popup": {
      "readMessage": "Read your boss's message to unlock",
      "startChallenge": "Start challenge 1 to unlock",
      "playChallenge": "Play challenge 1 to unlock",
      "completeChallenge1": "Complete challenge 1 before unlocking",
      "readMessageChallenge2": "Read challenge 2 instructions to unlock",
      "playChallenge2": "Play challenge 2 to unlock",
      "completeChallenge2": "Complete challenge 2 before unlocking",
      "readMessageChallenge3": "Read challenge 3 instructions to unlock",
      "readMessageChallengeFinal": "Read final challenge instructions to unlock",
      "playChallenge3": "Play challenge 3 to unlock",
      "completeChallenge3": "Complete challenge 3 before unlocking",
      "completeAllChallenges": "Complete all challenges to unlock"
    }
  },
  "messagesApp": {
    "title": "Messages",
    "inbox": "Inbox",
    "selectMessage": "Select a message to read",
    "fromLabel": "From",
    "chatPlaceholder": "Type a message...",
    "send": "Send",
    "newMessageNotification": "You have a new message!",
    "time": {
      "minutesAgo": "{{count}} min ago",
      "hoursAgo": "{{count}} h ago"
    },
    "messages": {
      "missionBrief": {
        "from": "Security Team",
        "subject": "🛡️ Suspicious users detected on ECHO",
        "content": "Moderator,\n\nThe ECHO network has detected several suspicious users who may be bots spreading misinformation.\n\nYour mission is to investigate them and prevent them from manipulating conversations on the platform.\n\n🔎 Go to Suspicious Users and analyse the profiles to determine which accounts may be bots and which appear to be real users.\n\n💡 If you need help identifying the parameters that characterize a bot, use the hint button inside the challenge."
      },
      "congratulations": {
        "from": "Security Team",
        "subject": "🎉 Mission completed",
        "content": "Moderator,\n\nYou have successfully completed all the challenges and helped reduce misinformation on ECHO.\n\nThanks to your decisions, the platform is now safer for the community."
      },
      "challenge2": {
        "from": "Security Team",
        "subject": "🤖 Possible AI-generated posts detected",
        "content": "Moderator,\n\nWe are detecting posts that may have been generated by artificial intelligence and could spread misinformation.\n\nOur automatic detector is currently under maintenance, so we need you to review a post manually.\n\n🧠 Go to AI Generated Content and analyse the post to determine whether it may have been generated by AI."
      },
      "challenge3": {
        "from": "Security Team",
        "subject": "⚠️ Incorrect use of AI detected",
        "content": "Moderator,\n\nSome users are using artificial intelligence to obtain information, but not always responsibly.\n\nBlindly trusting AI may lead to mistakes or misinformation.\n\n🧭 Go to Incorrect Uses of AI and review each situation to choose the response that best advises the user."
      },
      "challengeFinal": {
        "from": "Security Team",
        "subject": "📝 Final task: Community Note",
        "content": "Moderator,\n\nYou have helped identify bots and analyse the use of artificial intelligence on the platform.\n\nNow we need a clear message to help other users recognise misinformation.\n\n📝 Go to New Post and select the two correct statements to create a Community Note for the ECHO community."
      }
    }
  },
  "socialLogin": {
    "title": "Sign in",
    "subtitle": "Access required to continue",
    "usernameLabel": "Username",
    "passwordLabel": "Password",
    "submit": "Enter",
    "errorInvalid": "Incorrect username or password"
  },
  "createPost": {
    "placeholder": "What is happening?!",
    "fileTooBig": "file must be less than 20mb",
    "invalidFileType": "file must be a Video (MP4/MOV) or an Image (JPEG/PNG)",
    "publish": "Post",
    "challengeLocked": "Challenge Locked",
    "completeChallenge1": "Complete the Admin challenge to unlock posting",
    "selectTwoCorrect": "You've protected ECHO from misinformation. Throughout this mission you learned to detect bots, verify sources and think critically. Now share that knowledge: select the 2 correct statements and publish your Community Note.",
    "incorrectSelection": "Incorrect selection. Try again!",
    "selected": "selected",
    "publishConclusion": "Publish ",
    "conclusionText": "To combat misinformation on social media, it is essential that you develop critical thinking and verify information before sharing it. Bots and fake accounts often show repetitive patterns, suspicious activity at irregular times, and identical content. Learn to identify them and protect your community! 🔍✅",
    "escapeRoomCompleted": "🎉 Escape Room Completed! Thank you for learning to identify misinformation!"
  },
  "post": {
    "editPost": "Edit Post",
    "deletePost": "Delete Post",
    "verifiedAccount": "Verified account",
    "linkCopied": "Link successfully copied"
  },
  "home": {
    "sortBy": {
      "trending": "Trending",
      "oldest": "Oldest",
      "latest": "Latest",
      "posts": "Posts"
    },
    "noPosts": "Sorry, there no posts to show! Follow people to see their posts."
  },
  "profile": {
    "noPosts": "You have not added any posts!",
    "editProfile": "Edit Profile",
    "following": "Following",
    "followers": "Followers",
    "posts": "Posts",
    "joined": "Joined",
    "follow": "Follow",
    "verifiedAccount": "Verified account",
    "backToGame": "Back to Game",
    "misinfoQuestion": "Does this profile spread misinformation?",
    "yes": "Yes",
    "no": "No",
    "classificationIncorrect": "Incorrect selection. Review the profile again.",
    "openQuiz": "Continue quiz",
    "classificationQuizTitle": "What characteristics of this profile make it classified as a disinformation account?",
    "sendQuizAnswer": "Submit answer",
    "closeQuiz": "Close quiz"
  },
  "explore": {
    "caughtUp": "You are all caught up!"
  },
  "admin": {
    "title": "Manage suspicious accounts",
    "users": "Users",
    "posts": "Posts",
    "suspectUsers": "Suspicious Users",
    "beforeStart": "Before you start...",
    "noSuspects": "No suspicious users at this time",
    "classified": "Classified",
    "submit": "Submit Classification",
    "resultTitle": "Your Classification Result",
    "perfectScore": "Perfect Score!",
    "score": "Score",
    "allCorrect": "Excellent! You've correctly identified all users.",
    "tryAgain": "Some classifications are incorrect. Try again!",
    "playAgain": "Play Again",
    "hintTitle": "Bot Account Indicators",
    "hintContent": {
      "temporalActivity": "Suspicious temporal activity: Posts at very regular intervals or unusual times",
      "repetitiveContent": "Repetitive content: Very similar or identical messages between posts",
      "excessLinks": "Excess links: Many posts with external links",
      "noInteraction": "No interaction: Doesn't respond to comments or mentions",
      "abnormalRatio": "Abnormal ratio: Many followers but little real interaction",
      "singleTopic": "Single topic: Only posts about a very specific topic",
      "recentAccount": "Recent account: New account with immediate high activity",
      "verified": "Verification batch:",
      "official": "Official account: It belongs to an official/public organisation"
    }
  },
  "editPost": {
    "title": "Edit Post",
    "save": "Save",
    "cancel": "Cancel"
  },
  "aiContentPage": {
    "title": "Welcome, Moderator!",
    "subtitle": "AI generated content",
    "pendingReviewCount": "{{count}} post",
    "pendingReviewText": "pending review to verify whether it was generated by AI.",
    "verifyButton": "Verify post →",
    "statsCount": "{{count}} posts",
    "statsText": "have been marked as AI generated in the last hour.",
    "card1Title": "Will Smith Eats Spaghetti",
    "card2Title": "Madrid Hit by Meteorite Strike This Morning",
    "tag": "AI GENERATED",
    "seeAll": "See all →",
    "noPendingReview": "No new posts detected for review."
  },
  "aiVerifyPage": {
    "title": "Verify AI generated content",
    "subtitle": "Prove the content of this post was generated by AI, to stop disinformation online.",
    "postTitle": "Critical Thinking 🍎🥑",
    "postDate": "2025-12-11T00:00:00.000Z",
    "stamp": "AI GENERATED??",
    "reminder": "But first, let us remember how an LLM works.",
    "back": "← Back",
    "start": "Let's do this!"
  },
  "aiVideoPage": {
    "title": "How does generative AI work?",
    "subtitle": "Watch how the detection process works.",
    "back": "← Back",
    "nextStep": "Next"
  },
  "aiPrompt": {
    "suspiciousBadge": "SUSPICIOUS PROMPT"
  },
  "aiChallengeBriefPage": {
    "title": "Verify AI generated content",
    "systemMessage": "The system found a <strong>possible prompt in MINT-AI that generated the post</strong>, through the comparison of words, tone and topics:",
    "explanation": "This prompt may have some clues.",
    "instructions": "To prove the post was generated by AI, you'll have to <strong>imitate the generation of the post</strong>, word by word.",
    "buttonText": "Verify post as AI →"
  },
  "aiGamePage": {
    "title": "Verify AI generated content",
    "subtitle": "Think like a machine! Which word is more likely to be generated next?",
    "success": "Congratulations! You've completed the sentence correctly.",
    "error": "❌ Wrong word. Try again from the beginning.",
    "back": "← Back",
    "finish": "Finish",
    "challengeCompleted": "Challenge complete! 🎉",
    "challengeCompletedMsg": "You've proven that the post's content was generated by generative AI."
  },
  "aiIncorrectUsesPage": {
    "title": "AI incorrect uses ⚠️",
    "subtitle": "Hello Moderator! Please reply to users with advice so they don't repeat these mistakes, which are leading to misinformation on Echo.",
    "instruction": "Select the reply option that represents an incorrect use of AI.",
    "unavailable": "This challenge is not available in the current language yet.",
    "sent": "Reply sent",
    "tryAgain": "Try again before sending a reply",
    "correct": "Correct!",
    "progress": "Case {{current}} of {{total}}",
    "next": "Next case",
    "finish": "Restart challenge",
    "cases": "[object Object],[object Object],[object Object]",
    "reply": "Reply",
    "challengeCompleted": "Challenge complete! 🎉",
    "challengeCompletedMsg": "You've correctly replied to all AI incorrect use cases."
  },
  "comments": {
    "placeholder": "Write a comment...",
    "post": "Post",
    "noComments": "No comments yet",
    "reply": "Reply",
    "edit": "Edit",
    "delete": "Delete",
    "save": "Save"
  },
  "time": {
    "justNow": "just now",
    "minuteAgo": "minute ago",
    "minutesAgo": "minutes ago",
    "hourAgo": "hour ago",
    "hoursAgo": "hours ago",
    "dayAgo": "day ago",
    "daysAgo": "days ago",
    "weekAgo": "week ago",
    "weeksAgo": "weeks ago",
    "monthAgo": "month ago",
    "monthsAgo": "months ago",
    "yearAgo": "year ago",
    "yearsAgo": "years ago"
  },
  "statsPanel": {
    "title": "System Status",
    "misinformationLevel": "Misinformation Level",
    "statusAlert": "ALERT",
    "statusSecure": "SECURE",
    "botModule": {
      "title": "Bot Network",
      "detected": "Bots detected",
      "suspicious": "Suspicious accounts",
      "note": "Coordinated activity detected on the network",
      "resolvedNote": "Bot network neutralized"
    },
    "aiModule": {
      "title": "AI Detector",
      "status": "OFFLINE",
      "statusOnline": "ONLINE",
      "detector": "Automatic detector disabled",
      "detectorOnline": "Automatic detector active",
      "manualMode": "Manual verification required",
      "aiContentRate": "Possible AI-generated posts",
      "reason": "Module disabled by the system",
      "resolvedNote": "AI detector restored and active"
    },
    "modModule": {
      "title": "Moderation",
      "status": "MANUAL",
      "manual": "Manual moderation active",
      "automated": "Automated moderation active",
      "misuse": "AI misuse cases",
      "integrity": "Content integrity",
      "low": "LOW",
      "high": "HIGH",
      "note": "Improper generative AI uses detected"
    },
    "doneModule": {
      "status": "RESOLVED",
      "note": "The network is protected. Great job!"
    }
  },
  "errors": {
    "pageNotFound": "Page not found",
    "goHome": "Go to Home"
  },
  "officialAccount": {
    "name": "ECHO Official Account",
    "handle": "@ECHO",
    "bio": "Discover the latest from the social network and chat with MINT AI, our intelligent assistant."
  },
  "hintsApp": {
    "title": "Hints",
    "selectContext": "How can we help you?",
    "puzzle": {
      "1": "Challenge 1: Suspicious Users",
      "2": "Challenge 2: AI-Generated Content",
      "3": "Challenge 3: Incorrect AI Uses",
      "4": "Challenge 4: Community Note"
    },
    "back": "Back"
  },
  "filesApp": {
    "title": "File Explorer",
    "thisPC": "This PC",
    "folders": {
      "documents": "Documents",
      "images": "Images",
      "echo": "ECHO"
    },
    "empty": "This folder is empty",
    "locked": "Restricted access",
    "lockedTitle": "Private folder",
    "lockedMessage": "You do not have permission to access this folder.",
    "items": "{{count}} items",
    "back": "Back"
  }
};