export const en = {
  nav: {
    home: "Home",
    explore: "Explore",
    profile: "Profile",
    admin: "Suspicious Accounts",
    aiContent: "AI Generated Content",
    aiIncorrectUses: "AI Incorrect Uses",
    newPost: "New Post",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Messages",
      social: "Social Network",
    },
    window: {
      minimize: "Minimize",
      close: "Close",
    },
    taskbar: {
      start: "Start",
    },
  },
  messagesApp: {
    title: "Messages",
    inbox: "Inbox",
    selectMessage: "Select a message to read",
    fromLabel: "From",
    newMessageNotification: "You have a new message!",
    newMessageFromBoss: "Your boss has a mission for you",
    congratulationNotification: "Your boss has sent you a congratulation",
    time: {
      minutesAgo: "{{count}} min ago",
      hoursAgo: "{{count}} h ago",
    },
    messages: {
      missionBrief: {
        from: "The Boss",
        subject: "🚨 CRITICAL MISSION: Misinformation Alert!",
        content:
          "🚨 URGENT!\n\nI'm sending you this message because the misinformation level on our platform has reached CRITICAL levels at 78%. This is a serious threat to the integrity of our network.\n\nYour mission:\nGo to the Admin Panel and correctly classify all the profiles as bots or real users. Your accuracy is crucial for fighting automated misinformation spread. Once you complete this perfectly, you'll reduce the misinformation level.\nThe fate of the network is in your hands.\n\n- The Boss",
      },
      congratulations: {
        from: "The Boss",
        subject: "🎉 Congratulations! Challenge Completed",
        content:
          "🎉 EXCELLENT WORK!\n\nYou have correctly classified all the profiles. Your accuracy has significantly reduced the misinformation level on our platform.\n\nNow comes the crucial part:\nI need you to publish a post on the social network to EDUCATE our community. Share what you've learned about:\n\n• How to identify bots and automated accounts\n• The misinformation patterns you observed\n• The importance of verifying information\n• How to protect yourself from manipulation\n\nYour post will be a Community Note that will help other users recognize and combat misinformation. It's your opportunity to show the learning objectives and make a real difference.\n\nThe community is counting on you!\n\n- The Boss",
      },
    },
  },
  createPost: {
    placeholder: "What is happening?!",
    fileTooBig: "file must be less than 20mb",
    invalidFileType: "file must be a Video (MP4/MOV) or an Image (JPEG/PNG)",
    publish: "Post",
    challengeLocked: "Challenge Locked",
    completeChallenge1: "Complete the Admin challenge to unlock posting",
    selectTwoCorrect: "Select 2 correct statements about misinformation and bots",
    selectTwoStatements: "Please select exactly 2 statements",
    incorrectSelection: "Incorrect selection. Try again!",
    selected: "selected",
    publishConclusion: "Publish Community Note",
    statement1: "Bots can be detected by consistent and repetitive activity patterns",
    statement2: "Verified accounts are always real accounts and can never be bots",
    statement3: "Verifying accounts with multiple information sources is key to combating misinformation",
    statement4: "Bots always have public profiles and never private ones",
    statement5: "Digital education is fundamental for users to identify false content",
    conclusionText: "To combat misinformation on social media, it is essential that you develop critical thinking and verify information before sharing it. Bots and fake accounts often show repetitive patterns, suspicious activity at irregular times, and identical content. Learn to identify them and protect your community! 🔍✅",
    escapeRoomCompleted: "🎉 Escape Room Completed! Thank you for learning to identify misinformation!",
  },
  post: {
    editPost: "Edit Post",
    deletePost: "Delete Post",
    verifiedAccount: "Verified account",
    linkCopied: "Link successfully copied",
  },
  home: {
    sortBy: {
      trending: "Trending",
      oldest: "Oldest",
      latest: "Latest",
      posts: "Posts",
    },
    noPosts: "Sorry, there no posts to show! Follow people to see their posts.",
  },
  profile: {
    noPosts: "You have not added any posts!",
    editProfile: "Edit Profile",
    following: "Following",
    followers: "Followers",
    posts: "Posts",
    joined: "Joined",
    follow: "Follow",
    verifiedAccount: "Verified account",    backToGame: "Back to Game",  },
  explore: {
    caughtUp: "You are all caught up!",
  },
  admin: {
    title: "Manage suspicious accounts",
    users: "Users",
    posts: "Posts",
    suspectUsers: "Suspicious Users",
    hint: "Hint",
    bot: "Bot",
    human: "Human",
    noSuspects: "No suspicious users at this time",
    userBlocked: "User blocked as AI",
    userClassified: "User classified as Human",
    classified: "Classified",
    submit: "Submit Classification",
    resultTitle: "Your Classification Result",
    perfectScore: "Perfect Score!",
    score: "Score",
    allCorrect: "Excellent! You've correctly identified all users.",
    tryAgain: "Some classifications are incorrect. Try again!",
    playAgain: "Play Again",
    hintTitle: "Bot Account Indicators",
    hintContent: {
      temporalActivity: "Suspicious temporal activity: Posts at very regular intervals or unusual times",
      repetitiveContent: "Repetitive content: Very similar or identical messages between posts",
      excessLinks: "Excess links: Many posts with external links",
      noInteraction: "No interaction: Doesn't respond to comments or mentions",
      abnormalRatio: "Abnormal ratio: Many followers but little real interaction",
      singleTopic: "Single topic: Only posts about a very specific topic",
      recentAccount: "Recent account: New account with immediate high activity",
    },
  },
  editPost: {
    title: "Edit Post",
    save: "Save",
    cancel: "Cancel",
  },
  comments: {
    placeholder: "Write a comment...",
    post: "Post",
    noComments: "No comments yet",
    reply: "Reply",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
  },
  time: {
    justNow: "just now",
    minuteAgo: "minute ago",
    minutesAgo: "minutes ago",
    hourAgo: "hour ago",
    hoursAgo: "hours ago",
    dayAgo: "day ago",
    daysAgo: "days ago",
    weekAgo: "week ago",
    weeksAgo: "weeks ago",
    monthAgo: "month ago",
    monthsAgo: "months ago",
    yearAgo: "year ago",
    yearsAgo: "years ago",
  },
  statsPanel: {
    title: "System Status",
    misinformationLevel: "Misinformation Level",
    suspiciousActivityDetected: "⚠️ Suspicious activity detected on the network",
    detailedAnalysis: "Detailed Analysis",
    postsLastHour: "Posts (recent days)",
    percentageAboveNormal: "{{percentage}}% above normal",
    newUsersLastHour: "New users (recent days)",
    massAccountCreation: "⚠️ Massive account creation detected",
    viralHashtags: "Viral Hashtags",
    botActivity: "Bot Activity",
    detected: "detected",
    suspiciousInteractions: "{{percentage}}% of suspicious interactions",
    averageEngagement: "Average Engagement",
    likes: "Likes",
    comments: "Comments",
    shares: "Shares",
    recentAccounts: "Recent Accounts (recent days)",
    abnormalProportionNewAccounts: "⚠️ Abnormal proportion of new accounts",
    tip: "💡 Tip: Investigate profiles with suspicious patterns",
    statusHigh: "HIGH",
    statusMedium: "MEDIUM",
    statusLow: "LOW",
    systemSecure: "System Status: All Clear!",
  },
  errors: {
    pageNotFound: "Page not found",
    goHome: "Go to Home",
  },
};
