export const es = {
  nav: {
    home: "Inicio",
    explore: "Explorar",
    profile: "Perfil",
    admin: "Admin",
    newPost: "Nueva Publicación",
  },
  header: {
    appName: "ECHO",
  },
  createPost: {
    placeholder: "¿Qué está pasando?",
    fileTooBig: "el archivo debe ser menor de 20mb",
    invalidFileType: "el archivo debe ser un Video (MP4/MOV) o una Imagen (JPEG/PNG)",
    publish: "Publicar",
  },
  post: {
    editPost: "Editar Publicación",
    deletePost: "Eliminar Publicación",
    verifiedAccount: "Cuenta verificada",
    linkCopied: "Enlace copiado exitosamente",
  },
  home: {
    sortBy: {
      trending: "Tendencias",
      oldest: "Más Antiguas",
      latest: "Más Recientes",
      posts: "Publicaciones",
    },
    noPosts: "¡Lo sentimos, no hay publicaciones para mostrar! Sigue a personas para ver sus publicaciones.",
  },
  profile: {
    noPosts: "¡No has añadido ninguna publicación!",
    editProfile: "Editar Perfil",
    following: "Siguiendo",
    followers: "Seguidores",
    posts: "Publicaciones",
    joined: "Se unió",
    follow: "Seguir",
    verifiedAccount: "Cuenta verificada",
    backToGame: "Volver al Juego",
  },
  explore: {
    caughtUp: "¡Estás al día!",
  },
  admin: {
    title: "Panel de Administración",
    users: "Usuarios",
    posts: "Publicaciones",
    suspectUsers: "Usuarios Sospechosos",
    hint: "Pista",
    bot: "Bot",
    human: "Humano",
    noSuspects: "No hay usuarios sospechosos en este momento",
    userBlocked: "Usuario bloqueado clasificado como IA",
    userClassified: "Usuario clasificado como Humano",
    classified: "Clasificados",
    submit: "Enviar Clasificación",
    resultTitle: "Resultado de tu Clasificación",
    perfectScore: "¡Puntuación Perfecta!",
    score: "Puntuación",
    allCorrect: "¡Excelente! Has identificado correctamente todos los usuarios.",
    tryAgain: "Algunas clasificaciones son incorrectas. ¡Inténtalo de nuevo!",
    playAgain: "Jugar de Nuevo",
    hintTitle: "Indicadores de cuenta Bot",
    hintContent: {
      temporalActivity: "Actividad temporal sospechosa: Publicaciones a intervalos muy regulares o en horarios poco naturales",
      repetitiveContent: "Contenido repetitivo: Mensajes muy similares o idénticos entre publicaciones",
      excessLinks: "Exceso de enlaces: Muchas publicaciones con enlaces externos",
      noInteraction: "Interacción nula: No responde a comentarios o menciones",
      abnormalRatio: "Ratio anormal: Muchos seguidos pero poca interacción real",
      singleTopic: "Tema único: Solo publica sobre un tema muy específico",
      recentAccount: "Cuenta reciente: Cuenta nueva con mucha actividad inmediata",
    },
  },
  editPost: {
    title: "Editar Publicación",
    save: "Guardar",
    cancel: "Cancelar",
  },
  comments: {
    placeholder: "Escribe un comentario...",
    post: "Publicar",
    noComments: "Aún no hay comentarios",
    reply: "Responder",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
  },
  time: {
    justNow: "justo ahora",
    minuteAgo: "hace un minuto",
    minutesAgo: "hace minutos",
    hourAgo: "hace una hora",
    hoursAgo: "hace horas",
    dayAgo: "hace un día",
    daysAgo: "hace días",
    weekAgo: "hace una semana",
    weeksAgo: "hace semanas",
    monthAgo: "hace un mes",
    monthsAgo: "hace meses",
    yearAgo: "hace un año",
    yearsAgo: "hace años",
  },
  errors: {
    pageNotFound: "Página no encontrada",
    goHome: "Ir al Inicio",
  },
};
