export const es = {
  nav: {
    home: "Inicio",
    explore: "Explorar",
    profile: "Perfil",
    admin: "Cuentas Sospechosas",
    aiContent: "Contenido Generado por IA",
    aiIncorrectUses: "Usos Incorrectos de IA",
    newPost: "Nueva Publicación",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Mensajes",
      social: "Red Social",
    },
    window: {
      minimize: "Minimizar",
      close: "Cerrar",
    },
    taskbar: {
      start: "Inicio",
    },
  },
  messagesApp: {
    title: "Mensajes",
    inbox: "Bandeja de entrada",
    selectMessage: "Selecciona un mensaje para leer",
    fromLabel: "De",
    newMessageNotification: "¡Tienes un mensaje nuevo!",
    newMessageFromBoss: "Tu jefe tiene una misión para ti",
    congratulationNotification: "Tu jefe te ha enviado una felicitación",
    time: {
      minutesAgo: "Hace {{count}} min",
      hoursAgo: "Hace {{count}} h",
    },
    messages: {
      missionBrief: {
        from: "El Jefe",
        subject: "🚨 MISIÓN CRÍTICA: ¡Alerta de Desinformación!",
        content:
          "🚨 ¡URGENTE!\n\nTe envío este mensaje porque el nivel de desinformación en nuestra plataforma ha alcanzado niveles CRÍTICOS del 78%. Esta es una amenaza seria para la integridad de nuestra red.\n\nTu misión:\nVe al Panel de Administración y clasifica correctamente todos los perfiles como bots o usuarios reales. Tu precisión es crucial para combatir la propagación automatizada de desinformación. Una vez que completes esto perfectamente, reducirás el nivel de desinformación. \nEl destino de la red está en tus manos.\n\n- El Jefe",
      },
      congratulations: {
        from: "El Jefe",
        subject: "🎉 ¡Felicitaciones! Reto Completado",
        content:
          "🎉 ¡EXCELENTE TRABAJO!\n\nHas clasificado correctamente todos los perfiles. Tu precisión ha reducido significativamente el nivel de desinformación en nuestra plataforma.\n\nAhora viene la parte crucial:\nNecesito que publiques un post en la red social para EDUCAR a nuestra comunidad. Comparte lo que has aprendido sobre:\n\n• Cómo identificar bots y cuentas automatizadas\n• Los patrones de desinformación que observaste\n• La importancia de verificar la información\n• Cómo protegerse de la manipulación\n\nTu post será una Community Note que ayudará a otros usuarios a reconocer y combatir la desinformación. Es tu oportunidad de mostrar los objetivos de aprendizaje y hacer una diferencia real.\n\n¡La comunidad cuenta contigo!\n\n- El Jefe",
      },
    },
  },
  createPost: {
    placeholder: "¿Qué está pasando?",
    fileTooBig: "el archivo debe ser menor de 20mb",
    invalidFileType: "el archivo debe ser un Video (MP4/MOV) o una Imagen (JPEG/PNG)",
    publish: "Publicar",
    challengeLocked: "Reto Bloqueado",
    completeChallenge1: "Completa el reto de Admin para desbloquear publicaciones",
    selectTwoCorrect: "Selecciona 2 afirmaciones correctas sobre desinformación y bots",
    selectTwoStatements: "Por favor selecciona exactamente 2 afirmaciones",
    incorrectSelection: "Selección incorrecta. ¡Intenta de nuevo!",
    selected: "seleccionados",
    publishConclusion: "Publicar Nota Comunitaria",
    statement1: "Los bots pueden detectarse por patrones de actividad consistentes y repetitivos",
    statement2: "Las cuentas verificadas siempre son cuentas reales y nunca pueden ser bots",
    statement3: "La verificación de cuentas con múltiples fuentes de información es clave para combatir la desinformación",
    statement4: "Los bots siempre tienen perfiles públicos y nunca privados",
    statement5: "La educación digital es fundamental para que los usuarios identifiquen contenido falso",
    conclusionText: "Para combatir la desinformación en redes sociales, es esencial que desarrolles pensamiento crítico y verifiques la información antes de compartirla. Los bots y cuentas falsas suelen mostrar patrones repetitivos, actividad sospechosa en horarios irregulares y contenido idéntico. ¡Aprende a identificarlos y protege tu comunidad! 🔍✅",
    escapeRoomCompleted: "🎉 ¡Escape Room Completado! ¡Gracias por aprender a identificar la desinformación!",
  },
  post: {
    editPost: "Editar Publicación",
    deletePost: "Eliminar Publicación",
    verifiedAccount: "Cuenta verificada",
    linkCopied: "Enlace copiado exitosamente",
  },
  home: {
    sortBy: {
      trending: "Tendencias",
      oldest: "Más Antiguas",
      latest: "Más Recientes",
      posts: "Publicaciones",
    },
    noPosts: "¡Lo sentimos, no hay publicaciones para mostrar! Sigue a personas para ver sus publicaciones.",
  },
  profile: {
    noPosts: "¡No has añadido ninguna publicación!",
    editProfile: "Editar Perfil",
    following: "Siguiendo",
    followers: "Seguidores",
    posts: "Publicaciones",
    joined: "Se unió",
    follow: "Seguir",
    verifiedAccount: "Cuenta verificada",
    backToGame: "Volver al Juego",
  },
  explore: {
    caughtUp: "¡Estás al día!",
  },
  admin: {
    title: "Administra las cuentas sospechosas",
    users: "Usuarios",
    posts: "Publicaciones",
    suspectUsers: "Usuarios Sospechosos",
    hint: "Pista",
    bot: "Bot",
    human: "Humano",
    noSuspects: "No hay usuarios sospechosos en este momento",
    userBlocked: "Usuario bloqueado clasificado como IA",
    userClassified: "Usuario clasificado como Humano",
    classified: "Clasificados",
    submit: "Enviar Clasificación",
    resultTitle: "Resultado de tu Clasificación",
    perfectScore: "¡Puntuación Perfecta!",
    score: "Puntuación",
    allCorrect: "¡Excelente! Has identificado correctamente todos los usuarios.",
    tryAgain: "Algunas clasificaciones son incorrectas. ¡Inténtalo de nuevo!",
    playAgain: "Jugar de Nuevo",
    hintTitle: "Indicadores de cuenta Bot",
    hintContent: {
      temporalActivity: "Actividad temporal sospechosa: Publicaciones a intervalos muy regulares o en horarios poco naturales",
      repetitiveContent: "Contenido repetitivo: Mensajes muy similares o idénticos entre publicaciones",
      excessLinks: "Exceso de enlaces: Muchas publicaciones con enlaces externos",
      noInteraction: "Interacción nula: No responde a comentarios o menciones",
      abnormalRatio: "Ratio anormal: Muchos seguidos pero poca interacción real",
      singleTopic: "Tema único: Solo publica sobre un tema muy específico",
      recentAccount: "Cuenta reciente: Cuenta nueva con mucha actividad inmediata",
    },
  },
  editPost: {
    title: "Editar Publicación",
    save: "Guardar",
    cancel: "Cancelar",
  },
  comments: {
    placeholder: "Escribe un comentario...",
    post: "Publicar",
    noComments: "Aún no hay comentarios",
    reply: "Responder",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
  },
  time: {
    justNow: "justo ahora",
    minuteAgo: "hace un minuto",
    minutesAgo: "hace minutos",
    hourAgo: "hace una hora",
    hoursAgo: "hace horas",
    dayAgo: "hace un día",
    daysAgo: "hace días",
    weekAgo: "hace una semana",
    weeksAgo: "hace semanas",
    monthAgo: "hace un mes",
    monthsAgo: "hace meses",
    yearAgo: "hace un año",
    yearsAgo: "hace años",
  },
  statsPanel: {
    title: "Estado del Sistema",
    misinformationLevel: "Nivel de Desinformación",
    suspiciousActivityDetected: "⚠️ Actividad sospechosa detectada en la red",
    detailedAnalysis: "Análisis Detallado",
    postsLastHour: "Posts (últimos días)",
    percentageAboveNormal: "{{percentage}}% sobre lo normal",
    newUsersLastHour: "Nuevos usuarios (últimos días)",
    massAccountCreation: "⚠️ Creación masiva de cuentas detectada",
    viralHashtags: "Hashtags Virales",
    botActivity: "Actividad de Bots",
    detected: "detectados",
    suspiciousInteractions: "{{percentage}}% de interacciones sospechosas",
    averageEngagement: "Engagement Promedio",
    likes: "Likes",
    comments: "Comentarios",
    shares: "Compartidos",
    recentAccounts: "Cuentas Recientes (últimos días)",
    abnormalProportionNewAccounts: "⚠️ Proporción anormal de cuentas nuevas",
    tip: "💡 Consejo: Investiga los perfiles con patrones sospechosos",
    statusHigh: "ALTO",
    statusMedium: "MEDIO",
    statusLow: "BAJO",
    systemSecure: "¡Estado del Sistema: Todo Despejado!",
  },
  errors: {
    pageNotFound: "Página no encontrada",
    goHome: "Ir al Inicio",
  },
};
