export const es = {
  nav: {
    home: "Inicio",
    explore: "Explorar",
    profile: "Perfil",
    admin: "Admin",
    newPost: "Nueva Publicación",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Mensajes",
      social: "Red Social",
    },
    window: {
      minimize: "Minimizar",
      close: "Cerrar",
    },
    taskbar: {
      start: "Inicio",
    },
  },
  messagesApp: {
    title: "Mensajes",
    inbox: "Bandeja de entrada",
    selectMessage: "Selecciona un mensaje para leer",
    fromLabel: "De",
    time: {
      minutesAgo: "Hace {{count}} min",
      hoursAgo: "Hace {{count}} h",
    },
    messages: {
      welcome: {
        from: "El Jefe",
        subject: "Bienvenida al equipo",
        content:
          "¡Bienvenido/a a nuestro equipo de investigación! Tu primera misión es familiarizarte con la red social corporativa. Explora los perfiles y busca pistas.",
      },
      hint1: {
        from: "El Jefe",
        subject: "Primera pista",
        content:
          "He notado actividad sospechosa en algunos perfiles. Revisa los posts recientes y busca patrones inusuales. El usuario @admin podría tener información relevante.",
      },
      hint2: {
        from: "El Jefe",
        subject: "Pista adicional",
        content:
          "Los comentarios en los posts más populares podrían contener códigos ocultos. Presta atención a las palabras en mayúsculas y los emojis repetidos.",
      },
    },
  },
  createPost: {
    placeholder: "¿Qué está pasando?",
    fileTooBig: "el archivo debe ser menor de 20mb",
    invalidFileType: "el archivo debe ser un Video (MP4/MOV) o una Imagen (JPEG/PNG)",
    publish: "Publicar",
  },
  post: {
    editPost: "Editar Publicación",
    deletePost: "Eliminar Publicación",
    verifiedAccount: "Cuenta verificada",
    linkCopied: "Enlace copiado exitosamente",
  },
  home: {
    sortBy: {
      trending: "Tendencias",
      oldest: "Más Antiguas",
      latest: "Más Recientes",
      posts: "Publicaciones",
    },
    noPosts: "¡Lo sentimos, no hay publicaciones para mostrar! Sigue a personas para ver sus publicaciones.",
  },
  profile: {
    noPosts: "¡No has añadido ninguna publicación!",
    editProfile: "Editar Perfil",
    following: "Siguiendo",
    followers: "Seguidores",
    posts: "Publicaciones",
    joined: "Se unió",
    follow: "Seguir",
    verifiedAccount: "Cuenta verificada",
    backToGame: "Volver al Juego",
  },
  explore: {
    caughtUp: "¡Estás al día!",
  },
  admin: {
    title: "Panel de Administración",
    users: "Usuarios",
    posts: "Publicaciones",
    suspectUsers: "Usuarios Sospechosos",
    hint: "Pista",
    bot: "Bot",
    human: "Humano",
    noSuspects: "No hay usuarios sospechosos en este momento",
    userBlocked: "Usuario bloqueado clasificado como IA",
    userClassified: "Usuario clasificado como Humano",
    classified: "Clasificados",
    submit: "Enviar Clasificación",
    resultTitle: "Resultado de tu Clasificación",
    perfectScore: "¡Puntuación Perfecta!",
    score: "Puntuación",
    allCorrect: "¡Excelente! Has identificado correctamente todos los usuarios.",
    tryAgain: "Algunas clasificaciones son incorrectas. ¡Inténtalo de nuevo!",
    playAgain: "Jugar de Nuevo",
    hintTitle: "Indicadores de cuenta Bot",
    hintContent: {
      temporalActivity: "Actividad temporal sospechosa: Publicaciones a intervalos muy regulares o en horarios poco naturales",
      repetitiveContent: "Contenido repetitivo: Mensajes muy similares o idénticos entre publicaciones",
      excessLinks: "Exceso de enlaces: Muchas publicaciones con enlaces externos",
      noInteraction: "Interacción nula: No responde a comentarios o menciones",
      abnormalRatio: "Ratio anormal: Muchos seguidos pero poca interacción real",
      singleTopic: "Tema único: Solo publica sobre un tema muy específico",
      recentAccount: "Cuenta reciente: Cuenta nueva con mucha actividad inmediata",
    },
  },
  editPost: {
    title: "Editar Publicación",
    save: "Guardar",
    cancel: "Cancelar",
  },
  comments: {
    placeholder: "Escribe un comentario...",
    post: "Publicar",
    noComments: "Aún no hay comentarios",
    reply: "Responder",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
  },
  time: {
    justNow: "justo ahora",
    minuteAgo: "hace un minuto",
    minutesAgo: "hace minutos",
    hourAgo: "hace una hora",
    hoursAgo: "hace horas",
    dayAgo: "hace un día",
    daysAgo: "hace días",
    weekAgo: "hace una semana",
    weeksAgo: "hace semanas",
    monthAgo: "hace un mes",
    monthsAgo: "hace meses",
    yearAgo: "hace un año",
    yearsAgo: "hace años",
  },
  statsPanel: {
    title: "Estado del Sistema",
    misinformationLevel: "Nivel de Desinformación",
    suspiciousActivityDetected: "⚠️ Actividad sospechosa detectada en la red",
    detailedAnalysis: "Análisis Detallado",
    postsLastHour: "Posts (últimos días)",
    percentageAboveNormal: "{{percentage}}% sobre lo normal",
    newUsersLastHour: "Nuevos usuarios (últimos días)",
    massAccountCreation: "⚠️ Creación masiva de cuentas detectada",
    viralHashtags: "Hashtags Virales",
    botActivity: "Actividad de Bots",
    detected: "detectados",
    suspiciousInteractions: "{{percentage}}% de interacciones sospechosas",
    averageEngagement: "Engagement Promedio",
    likes: "Likes",
    comments: "Comentarios",
    shares: "Compartidos",
    recentAccounts: "Cuentas Recientes (últimos días)",
    abnormalProportionNewAccounts: "⚠️ Proporción anormal de cuentas nuevas",
    tip: "💡 Consejo: Investiga los perfiles con patrones sospechosos",
    statusHigh: "ALTO",
    statusMedium: "MEDIO",
    statusLow: "BAJO",
    systemSecure: "¡Estado del Sistema: Todo Despejado!",
  },
  errors: {
    pageNotFound: "Página no encontrada",
    goHome: "Ir al Inicio",
  },
};
