export const fi = {
  nav: {
    home: "Koti",
    explore: "Tutki",
    profile: "Profiili",
    admin: "Epäilyttävät Tilit",
    aiContent: "Tekoälyn Luoma Sisältö",
    aiIncorrectUses: "Tekoälyn Väärinkäyttö",
    newPost: "Uusi Julkaisu",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Viestit",
      social: "Sosiaalinen verkko",
    },
    window: {
      minimize: "Pienennä",
      close: "Sulje",
    },
    taskbar: {
      start: "Aloita",
    },
  },
  messagesApp: {
    title: "Viestit",
    inbox: "Saapuneet",
    selectMessage: "Valitse viesti luettavaksi",
    fromLabel: "Lähettäjä",
    newMessageNotification: "Sinulla on uusi viesti!",
    newMessageFromBoss: "Pomollasi on sinulle tehtävä",
    congratulationNotification: "Pomosi on lähettänyt sinulle onnittelut",
    time: {
      minutesAgo: "{{count}} min sitten",
      hoursAgo: "{{count}} h sitten",
    },
    messages: {
      missionBrief: {
        from: "Esimies",
        subject: "🚨 KRIITTINEN TEHTÄVÄ: Dezinformaation Hälytys!",
        content:
          "🚨 KIIREELLINEN!\n\nLähetän sinulle tämän viestin, koska dezinformaation taso alustalla on saavuttanut KRIITTISET tasot 78%. Tämä on vakava uhka verkkomme koskemattomuudelle.\n\nSinun tehtäväsi:\nMene hallintopaneeliin ja luokittele kaikki profiilit oikein botteihin tai oikeisiin käyttäjiin. Tarkkuutesi on ratkaisevan tärkeä automatisoidun dezinformaation leviämisen vastustamisessa. Kun suoritat tämän täydellisesti, pienennät dezinformaation tasoa.\nVerkon kohtalo on sinun käsissäsi.\n\n- Esimies",
      },
      congratulations: {
        from: "Esimies",
        subject: "🎉 Onnittelut! Haaste Suoritettu",
        content:
          "🎉 ERINOMAISTA TYÖTÄ!\n\nOlet luokitellut kaikki profiilit oikein. Tarkkuutesi on merkittävästi pienentänyt dezinformaation tasoa alustallamme.\n\nNyt tulee ratkaiseva osa:\nTarvitsen sinun julkaisevan julkaisun sosiaalisessa verkostossa KOULUTTAAKSESI yhteisöämme. Jaa mitä olet oppinut:\n\n• Kuinka tunnistaa botteja ja automatisoituja tilejä\n• Havaitut dezinformaation mallit\n• Tiedon tarkistamisen tärkeys\n• Kuinka suojautua manipulaatiolta\n\nJulkaisusi on Yhteisön Huomautus, joka auttaa muita käyttäjiä tunnistamaan ja taistelemaan dezinformaatiota vastaan. Tämä on tilaisuutesi näyttää oppimisen tavoitteet ja tehdä todellinen ero.\n\nYhteisö luottaa sinuun!\n\n- Esimies",
      },
    },
  },
  createPost: {
    placeholder: "Mitä tapahtuu?",
    fileTooBig: "tiedoston on oltava alle 20 mb",
    invalidFileType: "tiedoston on oltava video (MP4/MOV) tai kuva (JPEG/PNG)",
    publish: "Julkaise",
    challengeLocked: "Haaste Lukittu",
    completeChallenge1: "Suorita Admin-haaste voidaksesi lähettää viestejä",
    selectTwoCorrect: "Valitse 2 oikeaa väitettä väärätiedoista ja boteista",
    selectTwoStatements: "Valitse tarkasti 2 väitettä",
    incorrectSelection: "Väärä valinta. Yritä uudelleen!",
    selected: "valittu",
    publishConclusion: "Julkaise Yhteisömuistion",
    statement1: "Botit voidaan havaita johdonmukaisista ja toistuvista aktiviteettimuodoista",
    statement2: "Vahvistetut tilit ovat aina todellisia tilejä eivätkä voi koskaan olla botteja",
    statement3: "Tilien vahvistaminen useiden tietolähteiden avulla on avainasemassa väärätiedon torjunnassa",
    statement4: "Boteilla on aina julkiset profiilit eivätkä koskaan yksityiset",
    statement5: "Digitaalinen koulutus on olennaista, jotta käyttäjät voivat tunnistaa väärää sisältöä",
    conclusionText: "Dezinformaation vastaisesti sosiaalisessa mediassa on välttämätöntä, että kehität kriittistä ajattelua ja vahvistat tiedot ennen jakamista. Botit ja väärät tilit osoittavat usein toistuvia malleja, epäilyttävää toimintaa epäsäännöllisinä aikoina ja identtistä sisältöä. Opi tunnistamaan ne ja suojaa yhteisöäsi! 🔍✅",
    escapeRoomCompleted: "🎉 Escape Room Valmis! Kiitos siitä, että opit tunnistamaan väärätietoa!",
  },
  post: {
    editPost: "Muokkaa Julkaisua",
    deletePost: "Poista Julkaisu",
    verifiedAccount: "Vahvistettu tili",
    linkCopied: "Linkki kopioitu onnistuneesti",
  },
  home: {
    sortBy: {
      trending: "Trendi",
      oldest: "Vanhimmat",
      latest: "Uusimmat",
      posts: "Julkaisut",
    },
    noPosts: "Valitettavasti ei ole julkaisuja näytettäväksi! Seuraa ihmisiä nähdäksesi heidän julkaisunsa.",
  },
  profile: {
    noPosts: "Et ole lisännyt yhtään julkaisua!",
    editProfile: "Muokkaa Profiilia",
    following: "Seuraat",
    followers: "Seuraajat",
    posts: "Julkaisut",
    joined: "Liittynyt",
    follow: "Seuraa",
    verifiedAccount: "Vahvistettu tili",    backToGame: "Takaisin Peliin",  },
  explore: {
    caughtUp: "Olet ajan tasalla!",
  },
  admin: {
    title: "Hallinnoi epäilyttäviä tilejä",
    users: "Käyttäjät",
    posts: "Julkaisut",
    suspectUsers: "Epäillyttävät Käyttäjät",
    hint: "Vihje",
    bot: "Botti",
    human: "Ihminen",
    noSuspects: "Ei epäiltyjä käyttäjiä tällä hetkellä",
    userBlocked: "Käyttäjä estetty tekolynä",
    userClassified: "Käyttäjä luokiteltu ihmiseksi",
    classified: "Luokiteltu",
    submit: "Lähetä Luokittelu",
    resultTitle: "Luokittelusi Tulos",
    perfectScore: "Täydellinen Pistemäärä!",
    score: "Pisteet",
    allCorrect: "Erinomaista! Olet tunnistanut kaikki käyttäjät oikein.",
    tryAgain: "Jotkut luokittelut ovat väärin. Yritä uudelleen!",
    playAgain: "Pelaa Uudelleen",
    hintTitle: "Bottitilin indikaattorit",
    hintContent: {
      temporalActivity: "Epäilyttävä ajallinen toiminta: Julkaisut hyvin säännöllisin väliajoin tai epätavallisina aikoina",
      repetitiveContent: "Toistuva sisältö: Hyvin samankaltaisia tai identtisiä viestejä julkaisujen välillä",
      excessLinks: "Liikaa linkkejä: Monia julkaisuja ulkoisilla linkeillä",
      noInteraction: "Ei vuorovaikutusta: Ei vastaa kommentteihin tai mainintoihin",
      abnormalRatio: "Epänormaali suhde: Monta seuraajaa mutta vähän todellista vuorovaikutusta",
      singleTopic: "Yksi aihe: Julkaisee vain hyvin tietystä aiheesta",
      recentAccount: "Tuore tili: Uusi tili välittömällä korkealla aktiivisuudella",
    },
  },
  editPost: {
    title: "Muokkaa Julkaisua",
    save: "Tallenna",
    cancel: "Peruuta",
  },
  comments: {
    placeholder: "Kirjoita kommentti...",
    post: "Lähetä",
    noComments: "Ei vielä kommentteja",
    reply: "Vastaa",
    edit: "Muokkaa",
    delete: "Poista",
    save: "Tallenna",
  },
  time: {
    justNow: "juuri nyt",
    minuteAgo: "minuutti sitten",
    minutesAgo: "minuuttia sitten",
    hourAgo: "tunti sitten",
    hoursAgo: "tuntia sitten",
    dayAgo: "päivä sitten",
    daysAgo: "päivää sitten",
    weekAgo: "viikko sitten",
    weeksAgo: "viikkoa sitten",
    monthAgo: "kuukausi sitten",
    monthsAgo: "kuukautta sitten",
    yearAgo: "vuosi sitten",
    yearsAgo: "vuotta sitten",
  },
  statsPanel: {
    title: "Järjestelmän Tila",
    misinformationLevel: "Väärätietojen Taso",
    suspiciousActivityDetected: "⚠️ Epäilyttävä toiminta havaittu verkossa",
    detailedAnalysis: "Yksityiskohtainen Analyysi",
    postsLastHour: "Julkaisut (viimeisten päivien)",
    percentageAboveNormal: "{{percentage}}% normaalin yläpuolella",
    newUsersLastHour: "Uudet käyttäjät (viimeisten päivien)",
    massAccountCreation: "⚠️ Joukkojen tilin luominen havaittu",
    viralHashtags: "Virusomaiset Hashtagit",
    botActivity: "Bottitoiminta",
    detected: "havaittu",
    suspiciousInteractions: "{{percentage}}% epäilyttävää vuorovaikutusta",
    averageEngagement: "Keskimääräinen Sitoutuminen",
    likes: "Tykkäykset",
    comments: "Kommentit",
    shares: "Jaot",
    recentAccounts: "Äskettäin Luodut Tilit (viimeisten päivien)",
    abnormalProportionNewAccounts: "⚠️ Epätavallinen osuus uusista tileistä",
    tip: "💡 Vihje: Tutki profiilit, joissa on epäilyttäviä kuvioita",
    statusHigh: "KORKEA",
    statusMedium: "KESKITASO",
    statusLow: "MATALA",
    systemSecure: "Järjestelmän Tila: Kaikki Selvää!",
  },
  errors: {
    pageNotFound: "Sivua ei löytynyt",
    goHome: "Mene Kotiin",
  },
};
