export const fi = {
  nav: {
    home: "Koti",
    explore: "Tutki",
    profile: "Profiili",
    admin: "Hallinta",
    newPost: "Uusi Julkaisu",
  },
  header: {
    appName: "ECHO",
  },
  createPost: {
    placeholder: "Mitä tapahtuu?",
    fileTooBig: "tiedoston on oltava alle 20 mb",
    invalidFileType: "tiedoston on oltava video (MP4/MOV) tai kuva (JPEG/PNG)",
    publish: "Julkaise",
  },
  post: {
    editPost: "Muokkaa Julkaisua",
    deletePost: "Poista Julkaisu",
    verifiedAccount: "Vahvistettu tili",
    linkCopied: "Linkki kopioitu onnistuneesti",
  },
  home: {
    sortBy: {
      trending: "Trendi",
      oldest: "Vanhimmat",
      latest: "Uusimmat",
      posts: "Julkaisut",
    },
    noPosts: "Valitettavasti ei ole julkaisuja näytettäväksi! Seuraa ihmisiä nähdäksesi heidän julkaisunsa.",
  },
  profile: {
    noPosts: "Et ole lisännyt yhtään julkaisua!",
    editProfile: "Muokkaa Profiilia",
    following: "Seuraat",
    followers: "Seuraajat",
    posts: "Julkaisut",
    joined: "Liittynyt",
    follow: "Seuraa",
    verifiedAccount: "Vahvistettu tili",    backToGame: "Takaisin Peliin",  },
  explore: {
    caughtUp: "Olet ajan tasalla!",
  },
  admin: {
    title: "Hallintapaneeli",
    users: "Käyttäjät",
    posts: "Julkaisut",
    suspectUsers: "Epäillyttävät Käyttäjät",
    hint: "Vihje",
    bot: "Botti",
    human: "Ihminen",
    noSuspects: "Ei epäiltyjä käyttäjiä tällä hetkellä",
    userBlocked: "Käyttäjä estetty tekolynä",
    userClassified: "Käyttäjä luokiteltu ihmiseksi",
    classified: "Luokiteltu",
    submit: "Lähetä Luokittelu",
    resultTitle: "Luokittelusi Tulos",
    perfectScore: "Täydellinen Pistemäärä!",
    score: "Pisteet",
    allCorrect: "Erinomaista! Olet tunnistanut kaikki käyttäjät oikein.",
    tryAgain: "Jotkut luokittelut ovat väärin. Yritä uudelleen!",
    playAgain: "Pelaa Uudelleen",
    hintTitle: "Bottitilin indikaattorit",
    hintContent: {
      temporalActivity: "Epäilyttävä ajallinen toiminta: Julkaisut hyvin säännöllisin väliajoin tai epätavallisina aikoina",
      repetitiveContent: "Toistuva sisältö: Hyvin samankaltaisia tai identtisiä viestejä julkaisujen välillä",
      excessLinks: "Liikaa linkkejä: Monia julkaisuja ulkoisilla linkeillä",
      noInteraction: "Ei vuorovaikutusta: Ei vastaa kommentteihin tai mainintoihin",
      abnormalRatio: "Epänormaali suhde: Monta seuraajaa mutta vähän todellista vuorovaikutusta",
      singleTopic: "Yksi aihe: Julkaisee vain hyvin tietystä aiheesta",
      recentAccount: "Tuore tili: Uusi tili välittömällä korkealla aktiivisuudella",
    },
  },
  editPost: {
    title: "Muokkaa Julkaisua",
    save: "Tallenna",
    cancel: "Peruuta",
  },
  comments: {
    placeholder: "Kirjoita kommentti...",
    post: "Lähetä",
    noComments: "Ei vielä kommentteja",
    reply: "Vastaa",
    edit: "Muokkaa",
    delete: "Poista",
    save: "Tallenna",
  },
  time: {
    justNow: "juuri nyt",
    minuteAgo: "minuutti sitten",
    minutesAgo: "minuuttia sitten",
    hourAgo: "tunti sitten",
    hoursAgo: "tuntia sitten",
    dayAgo: "päivä sitten",
    daysAgo: "päivää sitten",
    weekAgo: "viikko sitten",
    weeksAgo: "viikkoa sitten",
    monthAgo: "kuukausi sitten",
    monthsAgo: "kuukautta sitten",
    yearAgo: "vuosi sitten",
    yearsAgo: "vuotta sitten",
  },
  errors: {
    pageNotFound: "Sivua ei löytynyt",
    goHome: "Mene Kotiin",
  },
};
