export const fi = {
  nav: {
    home: "Koti",
    explore: "Tutki",
    profile: "Profiili",
    admin: "Hallinta",
    newPost: "Uusi Julkaisu",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Viestit",
      social: "Sosiaalinen verkko",
    },
    window: {
      minimize: "Pienennä",
      close: "Sulje",
    },
    taskbar: {
      start: "Aloita",
    },
  },
  messagesApp: {
    title: "Viestit",
    inbox: "Saapuneet",
    selectMessage: "Valitse viesti luettavaksi",
    fromLabel: "Lähettäjä",
    time: {
      minutesAgo: "{{count}} min sitten",
      hoursAgo: "{{count}} h sitten",
    },
    messages: {
      welcome: {
        from: "Esimies",
        subject: "Tervetuloa tiimiin",
        content:
          "Tervetuloa tutkimustiimiimme! Ensimmäinen tehtäväsi on tutustua yrityksen sosiaaliseen verkostoon. Tutki profiileja ja etsi vihjeitä.",
      },
      hint1: {
        from: "Esimies",
        subject: "Ensimmäinen vihje",
        content:
          "Olen huomannut epäilyttävää toimintaa joissakin profiileissa. Tarkista viimeaikaiset julkaisut ja etsi poikkeavia kuvioita. Käyttäjällä @admin voi olla oleellista tietoa.",
      },
      hint2: {
        from: "Esimies",
        subject: "Lisävihje",
        content:
          "Suosituimpien julkaisujen kommentit voivat sisältää piilotettuja koodeja. Kiinnitä huomiota ISOIHIN KIRJAIMIIN ja toistuviin emojeihin.",
      },
    },
  },
  createPost: {
    placeholder: "Mitä tapahtuu?",
    fileTooBig: "tiedoston on oltava alle 20 mb",
    invalidFileType: "tiedoston on oltava video (MP4/MOV) tai kuva (JPEG/PNG)",
    publish: "Julkaise",
  },
  post: {
    editPost: "Muokkaa Julkaisua",
    deletePost: "Poista Julkaisu",
    verifiedAccount: "Vahvistettu tili",
    linkCopied: "Linkki kopioitu onnistuneesti",
  },
  home: {
    sortBy: {
      trending: "Trendi",
      oldest: "Vanhimmat",
      latest: "Uusimmat",
      posts: "Julkaisut",
    },
    noPosts: "Valitettavasti ei ole julkaisuja näytettäväksi! Seuraa ihmisiä nähdäksesi heidän julkaisunsa.",
  },
  profile: {
    noPosts: "Et ole lisännyt yhtään julkaisua!",
    editProfile: "Muokkaa Profiilia",
    following: "Seuraat",
    followers: "Seuraajat",
    posts: "Julkaisut",
    joined: "Liittynyt",
    follow: "Seuraa",
    verifiedAccount: "Vahvistettu tili",    backToGame: "Takaisin Peliin",  },
  explore: {
    caughtUp: "Olet ajan tasalla!",
  },
  admin: {
    title: "Hallintapaneeli",
    users: "Käyttäjät",
    posts: "Julkaisut",
    suspectUsers: "Epäillyttävät Käyttäjät",
    hint: "Vihje",
    bot: "Botti",
    human: "Ihminen",
    noSuspects: "Ei epäiltyjä käyttäjiä tällä hetkellä",
    userBlocked: "Käyttäjä estetty tekolynä",
    userClassified: "Käyttäjä luokiteltu ihmiseksi",
    classified: "Luokiteltu",
    submit: "Lähetä Luokittelu",
    resultTitle: "Luokittelusi Tulos",
    perfectScore: "Täydellinen Pistemäärä!",
    score: "Pisteet",
    allCorrect: "Erinomaista! Olet tunnistanut kaikki käyttäjät oikein.",
    tryAgain: "Jotkut luokittelut ovat väärin. Yritä uudelleen!",
    playAgain: "Pelaa Uudelleen",
    hintTitle: "Bottitilin indikaattorit",
    hintContent: {
      temporalActivity: "Epäilyttävä ajallinen toiminta: Julkaisut hyvin säännöllisin väliajoin tai epätavallisina aikoina",
      repetitiveContent: "Toistuva sisältö: Hyvin samankaltaisia tai identtisiä viestejä julkaisujen välillä",
      excessLinks: "Liikaa linkkejä: Monia julkaisuja ulkoisilla linkeillä",
      noInteraction: "Ei vuorovaikutusta: Ei vastaa kommentteihin tai mainintoihin",
      abnormalRatio: "Epänormaali suhde: Monta seuraajaa mutta vähän todellista vuorovaikutusta",
      singleTopic: "Yksi aihe: Julkaisee vain hyvin tietystä aiheesta",
      recentAccount: "Tuore tili: Uusi tili välittömällä korkealla aktiivisuudella",
    },
  },
  editPost: {
    title: "Muokkaa Julkaisua",
    save: "Tallenna",
    cancel: "Peruuta",
  },
  comments: {
    placeholder: "Kirjoita kommentti...",
    post: "Lähetä",
    noComments: "Ei vielä kommentteja",
    reply: "Vastaa",
    edit: "Muokkaa",
    delete: "Poista",
    save: "Tallenna",
  },
  time: {
    justNow: "juuri nyt",
    minuteAgo: "minuutti sitten",
    minutesAgo: "minuuttia sitten",
    hourAgo: "tunti sitten",
    hoursAgo: "tuntia sitten",
    dayAgo: "päivä sitten",
    daysAgo: "päivää sitten",
    weekAgo: "viikko sitten",
    weeksAgo: "viikkoa sitten",
    monthAgo: "kuukausi sitten",
    monthsAgo: "kuukautta sitten",
    yearAgo: "vuosi sitten",
    yearsAgo: "vuotta sitten",
  },
  statsPanel: {
    title: "Järjestelmän Tila",
    misinformationLevel: "Väärätietojen Taso",
    suspiciousActivityDetected: "⚠️ Epäilyttävä toiminta havaittu verkossa",
    detailedAnalysis: "Yksityiskohtainen Analyysi",
    postsLastHour: "Julkaisut (viimeisten päivien)",
    percentageAboveNormal: "{{percentage}}% normaalin yläpuolella",
    newUsersLastHour: "Uudet käyttäjät (viimeisten päivien)",
    massAccountCreation: "⚠️ Joukkojen tilin luominen havaittu",
    viralHashtags: "Virusomaiset Hashtagit",
    botActivity: "Bottitoiminta",
    detected: "havaittu",
    suspiciousInteractions: "{{percentage}}% epäilyttävää vuorovaikutusta",
    averageEngagement: "Keskimääräinen Sitoutuminen",
    likes: "Tykkäykset",
    comments: "Kommentit",
    shares: "Jaot",
    recentAccounts: "Äskettäin Luodut Tilit (viimeisten päivien)",
    abnormalProportionNewAccounts: "⚠️ Epätavallinen osuus uusista tileistä",
    tip: "💡 Vihje: Tutki profiilit, joissa on epäilyttäviä kuvioita",
    statusHigh: "KORKEA",
    statusMedium: "KESKITASO",
    statusLow: "MATALA",
    systemSecure: "Järjestelmän Tila: Kaikki Selvää!",
  },
  errors: {
    pageNotFound: "Sivua ei löytynyt",
    goHome: "Mene Kotiin",
  },
};
