export const sr = {
  nav: {
    home: "Početna",
    explore: "Istraži",
    profile: "Profil",
    admin: "Admin",
    newPost: "Nova Objava",
  },
  header: {
    appName: "ECHO",
  },
  createPost: {
    placeholder: "Šta se dešava?",
    fileTooBig: "fajl mora biti manji od 20mb",
    invalidFileType: "fajl mora biti Video (MP4/MOV) ili Slika (JPEG/PNG)",
    publish: "Objavi",
  },
  post: {
    editPost: "Izmeni Objavu",
    deletePost: "Obriši Objavu",
    verifiedAccount: "Verifikovan nalog",
    linkCopied: "Link uspešno kopiran",
  },
  home: {
    sortBy: {
      trending: "Popularno",
      oldest: "Najstarije",
      latest: "Najnovije",
      posts: "Objave",
    },
    noPosts: "Žao nam je, nema objava za prikaz! Pratite ljude da vidite njihove objave.",
  },
  profile: {
    noPosts: "Niste dodali nijednu objavu!",
    editProfile: "Izmeni Profil",
    following: "Pratim",
    followers: "Pratioci",
    posts: "Objave",
    joined: "Pridružio se",
    follow: "Prati",
    verifiedAccount: "Verifikovan nalog",    backToGame: "Nazad na Igru",  },
  explore: {
    caughtUp: "Stigli ste do kraja!",
  },
  admin: {
    title: "Admin Panel",
    users: "Korisnici",
    posts: "Objave",
    suspectUsers: "Sumnjivi Korisnici",
    hint: "Savet",
    bot: "Bot",
    human: "Covek",
    noSuspects: "Nema sumnjivih korisnika u ovom trenutku",
    userBlocked: "Korisnik blokiran kao AI",
    userClassified: "Korisnik klasifikovan kao čovek",
    classified: "Klasifikovano",
    submit: "Pošalji Klasifikaciju",
    resultTitle: "Rezultat Vaše Klasifikacije",
    perfectScore: "Savršen Rezultat!",
    score: "Rezultat",
    allCorrect: "Odlično! Pravilno ste identifikovali sve korisnike.",
    tryAgain: "Neke klasifikacije su netačne. Pokušajte ponovo!",
    playAgain: "Igraj Ponovo",
    hintTitle: "Indikatori Bot naloga",
    hintContent: {
      temporalActivity: "Sumnjiva vremenska aktivnost: Objave u veoma redovnim intervalima ili neprirodno vreme",
      repetitiveContent: "Ponavljajući sadržaj: Veoma slične ili identične poruke između objava",
      excessLinks: "Previše linkova: Mnogo objava sa spoljšnjim linkovima",
      noInteraction: "Bez interakcije: Ne odgovara na komentare ili pominjanja",
      abnormalRatio: "Nenormalan odnos: Mnogo pratilaca ali malo prave interakcije",
      singleTopic: "Jedna tema: Objavljuje samo o veoma specifičnoj temi",
      recentAccount: "Skorija nalog: Nov nalog sa trenutnom visokom aktivnošću",
    },
  },
  editPost: {
    title: "Izmeni Objavu",
    save: "Sačuvaj",
    cancel: "Otkaži",
  },
  comments: {
    placeholder: "Napiši komentar...",
    post: "Objavi",
    noComments: "Još nema komentara",
    reply: "Odgovori",
    edit: "Izmeni",
    delete: "Obriši",
    save: "Sačuvaj",
  },
  time: {
    justNow: "upravo sada",
    minuteAgo: "pre minut",
    minutesAgo: "pre minuta",
    hourAgo: "pre sat",
    hoursAgo: "pre sati",
    dayAgo: "pre dan",
    daysAgo: "pre dana",
    weekAgo: "pre nedelju",
    weeksAgo: "pre nedelja",
    monthAgo: "pre mesec",
    monthsAgo: "pre meseci",
    yearAgo: "pre godinu",
    yearsAgo: "pre godina",
  },

  errors: {
    pageNotFound: "Stranica nije pronađena",
    goHome: "Idi na Početnu",
  },
};
