export const sr = {
  nav: {
    home: "Pocetna",
    explore: "Istra�i",
    profile: "Profil",
    admin: "Sumnjivi Nalozi",
    aiContent: "AI Generisan Sadr�aj",
    aiIncorrectUses: "Pogre�na Upotreba AI",
    newPost: "Nova Objava",
  },
  header: {
    appName: "ECHO",
  },
  desktop: {
    apps: {
      messages: "Poruke",
      social: "Dru�tvena mre�a",
    },
    window: {
      minimize: "Minimizuj",
      close: "Zatvori",
    },
    taskbar: {
      start: "Start",
    },
    popup: {
      readMessage: "Procitaj poruku svog sefa da otkljucas",
      startChallenge: "Zapocni izazov 1 da otkljucas",
      playChallenge: "Igraj izazov 1 da otkljucas",
      completeChallenge1: "Zavrsi izazov 1 pre otkljucavanja",
      readMessageChallenge2: "Procitaj uputstva za izazov 2 da otkljucas",
      playChallenge2: "Igraj izazov 2 da otkljucas",
      completeChallenge2: "Zavrsi izazov 2 pre otkljucavanja",
      readMessageChallenge3: "Procitaj uputstva za izazov 3 da otkljucas",
      readMessageChallengeFinal: "Procitaj uputstva za poslednji izazov da otkljucas",
      playChallenge3: "Igraj izazov 3 da otkljucas",
      completeChallenge3: "Zavrsi izazov 3 pre otkljucavanja",
      completeAllChallenges: "Zavrsi sve izazove da otkljucas",
    },
  },
  messagesApp: {
    title: "Poruke",
    inbox: "Prijemno sanduce",
    selectMessage: "Izaberi poruku za citanje",
    fromLabel: "Od",
    chatPlaceholder: "Napisi poruku...",
    send: "Posalji",
    newMessageNotification: "Imate novu poruku!",
    newMessageFromBoss: "Va� �ef ima misiju za vas",
    congratulationNotification: "Va� �ef vam je poslao cestitke",
    time: {
      minutesAgo: "pre {{count}} min",
      hoursAgo: "pre {{count}} h",
    },
    messages: {
      missionBrief: {
        from: "�ef",
        subject: "?? KRITICNA MISIJA: Upozorenje o Dezinformaciji!",
        content:
          "KRITICNI ALARM: mreza je ugrozena.\n\nIzazov 1:\nOtvori Sumnjive Naloge i pronadji botove.\n\nAko ne uspes, dezinformacije rastu. Resi odmah.\n\n- Sef",
      },
      congratulations: {
        from: "�ef",
        subject: "?? Cestitamo! Izazov Zavr�en",
        content:
          "Odlican posao, prva pretnja je zaustavljena.\n\nPredji odmah na izazov 2 i proveri AI sadrzaj.\n\n- Sef",
      },
    },
  },
  createPost: {
    placeholder: "�ta se de�ava?",
    fileTooBig: "fajl mora biti manji od 20mb",
    invalidFileType: "fajl mora biti Video (MP4/MOV) ili Slika (JPEG/PNG)",
    publish: "Objavi",
    challengeLocked: "Izazov Zakljucan",
    completeChallenge1: "Zavr�i Admin izazov da otkljuca� objavljivanje",
    selectTwoCorrect: "Izaberi 2 ispravne tvrdnje o dezinformaciji i botovima",
    selectTwoStatements: "Molim te izaberi tacno 2 tvrdnje",
    incorrectSelection: "Pogre�an izbor. Poku�aj ponovo!",
    selected: "izabrano",
    publishConclusion: "Objavi Zajednicku Bele�ku",
    conclusionText: "Za borbu protiv dezinformacije na dru�tvenim mre�ama, neophodno je da razvijete kriticko razmi�ljanje i da verifikujete informacije pre nego �to ih podelite. Botovi i la�ni nalozi cesto pokazuju repetitivne �ablone, sumnjive aktivnosti u neregularnim vremenima i identican sadr�aj. Naucite da ih prepoznate i �titite svoju zajednicu! ???",
    escapeRoomCompleted: "?? Escape Room Zavr�en! Hvala �to ste naucili prepoznavati dezinformaciju!",
  },
  post: {
    editPost: "Izmeni Objavu",
    deletePost: "Obri�i Objavu",
    verifiedAccount: "Verifikovan nalog",
    linkCopied: "Link uspe�no kopiran",
  },
  home: {
    sortBy: {
      trending: "Popularno",
      oldest: "Najstarije",
      latest: "Najnovije",
      posts: "Objave",
    },
    noPosts: "�ao nam je, nema objava za prikaz! Pratite ljude da vidite njihove objave.",
  },
  profile: {
    noPosts: "Niste dodali nijednu objavu!",
    editProfile: "Izmeni Profil",
    following: "Pratim",
    followers: "Pratioci",
    posts: "Objave",
    joined: "Pridru�io se",
    follow: "Prati",
    verifiedAccount: "Verifikovan nalog",    backToGame: "Nazad na Igru",  },
  explore: {
    caughtUp: "Stigli ste do kraja!",
  },
  admin: {
    title: "Upravljaj sumnjivim nalozima",
    users: "Korisnici",
    posts: "Objave",
    suspectUsers: "Sumnjivi Korisnici",
    hint: "Savet",
    bot: "Bot",
    human: "Covek",
    noSuspects: "Nema sumnjivih korisnika u ovom trenutku",
    userBlocked: "Korisnik blokiran kao AI",
    userClassified: "Korisnik klasifikovan kao covek",
    classified: "Klasifikovano",
    submit: "Po�alji Klasifikaciju",
    resultTitle: "Rezultat Va�e Klasifikacije",
    perfectScore: "Savr�en Rezultat!",
    score: "Rezultat",
    allCorrect: "Odlicno! Pravilno ste identifikovali sve korisnike.",
    tryAgain: "Neke klasifikacije su netacne. Poku�ajte ponovo!",
    playAgain: "Igraj Ponovo",
    hintTitle: "Indikatori Bot naloga",
    hintContent: {
      temporalActivity: "Sumnjiva vremenska aktivnost: Objave u veoma redovnim intervalima ili neprirodno vreme",
      repetitiveContent: "Ponavljajuci sadr�aj: Veoma slicne ili identicne poruke izmedu objava",
      excessLinks: "Previ�e linkova: Mnogo objava sa spolj�njim linkovima",
      noInteraction: "Bez interakcije: Ne odgovara na komentare ili pominjanja",
      abnormalRatio: "Nenormalan odnos: Mnogo pratilaca ali malo prave interakcije",
      singleTopic: "Jedna tema: Objavljuje samo o veoma specificnoj temi",
      recentAccount: "Skorija nalog: Nov nalog sa trenutnom visokom aktivno�cu",
    },
  },
  editPost: {
    title: "Izmeni Objavu",
    save: "Sacuvaj",
    cancel: "Otka�i",
  },
  comments: {
    placeholder: "Napi�i komentar...",
    post: "Objavi",
    noComments: "Jo� nema komentara",
    reply: "Odgovori",
    edit: "Izmeni",
    delete: "Obri�i",
    save: "Sacuvaj",
  },
  time: {
    justNow: "upravo sada",
    minuteAgo: "pre minut",
    minutesAgo: "pre minuta",
    hourAgo: "pre sat",
    hoursAgo: "pre sati",
    dayAgo: "pre dan",
    daysAgo: "pre dana",
    weekAgo: "pre nedelju",
    weeksAgo: "pre nedelja",
    monthAgo: "pre mesec",
    monthsAgo: "pre meseci",
    yearAgo: "pre godinu",
    yearsAgo: "pre godina",
  },

  statsPanel: {
    title: "Status Sistema",
    misinformationLevel: "Nivo Dezinformacija",
    suspiciousActivityDetected: "?? Sumnjiva aktivnost otkrivena na mre�i",
    detailedAnalysis: "Detaljne Analize",
    postsLastHour: "Objave (poslednjih dana)",
    percentageAboveNormal: "{{percentage}}% iznad normalnog",
    newUsersLastHour: "Novi korisnici (poslednjih dana)",
    massAccountCreation: "?? Masovna kreiranje naloga otkriveno",
    viralHashtags: "Virusni He�tegovi",
    botActivity: "Aktivnost Botova",
    detected: "otkriveni",
    suspiciousInteractions: "{{percentage}}% sumnjive interakcije",
    averageEngagement: "Prosecna Anga�ovanost",
    likes: "Lajkovi",
    comments: "Komentari",
    shares: "Deljenja",
    recentAccounts: "Nedavni Nalozi (poslednjih dana)",
    abnormalProportionNewAccounts: "?? Neobican odnos novih naloga",
    tip: "?? Savet: Istra�ite profile sa sumnjivim obrascima",
    statusHigh: "VISOK",
    statusMedium: "SREDNJI",
    statusLow: "NIZAK",
    systemSecure: "Status Sistema: Sve Je Cisto!",
  },
  errors: {
    pageNotFound: "Stranica nije pronadena",
    goHome: "Idi na Pocetnu",
  },
};


